[package]
name = "rust_barcode_reader"
version = "0.3.0"
authors = ["mait <mait.sarv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.2"